[General]
# Keep general settings here (logging, etc.)

[UartEndpoint FlightController]
# This replaces /dev/ttyACM0:921600 from your command line
Device = /dev/ttyACM0
Baud = 921600

[UdpEndpoint QGC]
Mode = Normal
Address = 192.168.209.204
Port = 14550

[UdpEndpoint MAVSDK]
Mode = Normal
Address = 127.0.0.1
Port = 14600

[UdpEndpoint Mocap]
Mode = Normal
Address = 192.168.209.204
Port = 14553
# Blocks high-rate drone telemetry from flowing back to your laptop over this port.
# It will only pass the low-frequency HEARTBEAT (Message ID 0).
AllowMsgIdOut = 0
